// <auto-generated />
namespace SampleWebApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ExtraOAuthData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExtraOAuthData));
        
        string IMigrationMetadata.Id
        {
            get { return "201209262357212_ExtraOAuthData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
